package tech.clegg.gradeer.solution;

import tech.clegg.gradeer.checks.Check;
import tech.clegg.gradeer.checks.checkresults.CheckResult;
import tech.clegg.gradeer.preprocessing.PreProcessor;
import tech.clegg.gradeer.preprocessing.PreProcessorResults;
import tech.clegg.gradeer.subject.JavaSource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

public class Solution
{
    Path directory;
    Collection<JavaSource> sources;

    private Map<Class<? extends PreProcessor>, PreProcessorResults> preProcessorResults;

    private Collection<String> flags = Collections.newSetFromMap(new ConcurrentHashMap<>());
    private Map<Check, CheckResult> checkResultsMap = new ConcurrentHashMap<>();

    public Solution(Path locationDir)
    {
        this.directory = locationDir;
        this.preProcessorResults = new HashMap<>();
        try
        {
            sources = Files.walk(directory)
                    .filter(p -> com.google.common.io.Files.getFileExtension(p.toString()).equals("java"))
                    // Remove the hidden files generated by OSX, can't be parsed correctly.
                    .filter(p -> !p.toString().contains("__MACOSX"))
                    .map(p -> new JavaSource(p, locationDir))
                    .collect(Collectors.toList());
        } catch (IOException e)
        {
            e.printStackTrace();
        }
    }

    public void checkForMissingSources(Collection<String> complexClassNames)
    {
        if (complexClassNames == null || complexClassNames.isEmpty())
            return;

        Collection<String> presentClasses = sources.stream()
                .map(JavaSource::getComplexClassName)
                .collect(Collectors.toSet());

        Collection<String> missing = new HashSet<>();

        for (String c : complexClassNames)
        {
            if(!presentClasses.contains(c))
            {
                missing.add(c);
            }
        }

        if(!missing.isEmpty())
        {
            addFlag(DefaultFlag.MISSING_CLASS);
            System.err.println("Solution " + getIdentifier() + " has missing required class(es):");
            System.err.println(missing);
            System.err.println("\n");
        }

    }

    public void addPreProcessorResults(Class<? extends PreProcessor> type, PreProcessorResults results)
    {
        preProcessorResults.put(type, results);
    }

    public Collection<PreProcessorResults> getAllPreProcessorResults()
    {
        return preProcessorResults.values();
    }

    public PreProcessorResults getPreProcessorResultsOfType(Class<? extends PreProcessor> type)
            throws NoSuchElementException
    {
        PreProcessorResults r = preProcessorResults.getOrDefault(type, null);
        if(r != null)
            return r;
        throw new NoSuchElementException("No PreProcessorResults for PreProcessor " + type.getSimpleName());
    }

    public boolean hasPreProcessorResultsOfType(Class<? extends PreProcessor> type)
    {
        try
        {
            getPreProcessorResultsOfType(type);
            return true;
        } catch (NoSuchElementException e)
        {
           return false;
        }
    }

    public Path getDirectory()
    {
        return directory;
    }

    public Collection<JavaSource> getSources()
    {
        return sources;
    }

    public void addSource(JavaSource javaSourceToAdd)
    {
        sources.add(javaSourceToAdd);
    }

    public String getIdentifier()
    {
        return directory.getFileName().toString();
    }

    public boolean isCompiled()
    {
        for (JavaSource s : sources)
        {
            if(!s.isCompiled())
                return false;
        }
        return true;
    }

    public void addFlags(Collection<String> flagCollection)
    {
        flags.addAll(flagCollection);
    }

    public void addFlag(DefaultFlag flag)
    {
        addFlag(flag.name());
    }

    public void addFlag(String flag)
    {
        flags.add(flag);
    }

    public Collection<String> getFlags()
    {
        return flags;
    }

    public boolean containsFlag(String flag)
    {
        return flags.contains(flag);
    }

    public void addCheckResult(CheckResult result)
    {
        checkResultsMap.put(result.getCheck(), result);
    }

    public void addAllCheckResults(Collection<CheckResult> checkResults, boolean overwrite)
    {
        if (overwrite)
            checkResults.forEach(this::addCheckResult);
        else
        {
            for (CheckResult checkResult : checkResults)
            {
                if (!this.checkResultsMap.containsKey(checkResult.getCheck()))
                    addCheckResult(checkResult);
            }
        }
    }

    public CheckResult getCheckResult(Check check)
    {
        return checkResultsMap.get(check);
    }

    public double calculateWeightedScore(Check check)
    {
        return getCheckResult(check).getUnweightedScore() * check.getWeight();
    }

    public boolean hasCheckResult(Check check)
    {
        return checkResultsMap.containsKey(check);
    }

    public Collection<CheckResult> getAllCheckResults()
    {
        return checkResultsMap.values();
    }

    public void clearChecks(Collection<Check> checks)
    {
        for (Check c : checks)
            this.checkResultsMap.remove(c);
    }
}
